version: "3.8"

services:
  redis:
    image: redis:7.2-alpine
    container_name: demo3-redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: demo3-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    platform: linux/arm64
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: demo3-kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    platform: linux/arm64  

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: demo3-rabbitmq
    ports:
      - "5672:5672" 
      - "15672:15672" 

volumes:
  esdata:
